// Generated by scripts/generate_renderer_types.py. Do not edit.

export type ChartBlock = {
  "type": "bar" | "line" | "pie";
  "title"?: string | null;
  "unit"?: string | null;
  "labels"?: (string)[];
  "series"?: (ChartSeries)[];
  "data"?: (PieItem)[];
  "show_legend"?: boolean;
};

export type ChartSeries = {
  "name": string;
  "values": (number)[];
};

export type PieItem = {
  "name": string;
  "value": number;
};

export type StatItem = {
  "label": string;
  "value": string;
  "unit"?: string | null;
  "detail"?: string | null;
  "status"?: "neutral" | "success" | "warning" | "danger";
};

export type StatsBlock = {
  "title"?: string | null;
  "columns"?: number;
  "variant"?: "plain" | "cards";
  "items": (StatItem)[];
};

export type TimelineBlock = {
  "title"?: string | null;
  "items": (TimelineItem)[];
};

export type TimelineItem = {
  "time": string;
  "title": string;
  "content"?: string | null;
  "status"?: "neutral" | "success" | "warning" | "danger";
};

export type UIBadge = {
  "type": "badge";
  "text": string;
  "status"?: "neutral" | "success" | "warning" | "danger";
  "variant"?: "secondary" | "outline" | "solid";
};

export type UICallout = {
  "type": "alert" | "callout";
  "title"?: string | null;
  "text": string;
  "status"?: "neutral" | "success" | "warning" | "danger";
};

export type UICard = {
  "type": "card";
  "title"?: string | null;
  "description"?: string | null;
  "eyebrow"?: string | null;
  "footer"?: string | null;
  "variant"?: "outline" | "muted" | "ghost";
  "color"?: "neutral" | "blue" | "emerald" | "violet" | "amber" | "rose" | "cyan";
  "children": (UIText | UIProse | UIBadge | UILink | UICallout | UILayout | UICard | UISection | UISteps | UIList | UIFacts | UISeparator | UIQuote | UISources | UIProgress | UITable | UIImage | UIFrame | UIMap | UIChart | UIStats | UITimeline)[];
};

export type UIChart = {
  "type": "chart";
  "config": ChartBlock;
};

export type UIFact = {
  "label": string;
  "value": string;
};

export type UIFacts = {
  "type": "facts";
  "columns"?: number;
  "items": (UIFact)[];
};

export type UIFrame = {
  "type": "iframe";
  "url": string;
  "title": string;
  "height"?: number;
  "full_page"?: boolean;
  "caption"?: string | null;
};

export type UIImage = {
  "type": "image";
  "url": string;
  "alt": string;
  "caption"?: string | null;
  "fit"?: "contain" | "cover";
  "aspect"?: "original" | "landscape" | "portrait" | "square";
};

export type UIItem = {
  "title": string;
  "description"?: string | null;
  "meta"?: string | null;
};

export type UILayout = {
  "type": "row" | "column" | "grid";
  "columns"?: number;
  "children": (UIText | UIProse | UIBadge | UILink | UICallout | UILayout | UICard | UISection | UISteps | UIList | UIFacts | UISeparator | UIQuote | UISources | UIProgress | UITable | UIImage | UIFrame | UIMap | UIChart | UIStats | UITimeline)[];
  "gap"?: "sm" | "md" | "lg";
};

export type UILink = {
  "type": "link";
  "label": string;
  "url": string;
};

export type UIList = {
  "type": "list";
  "variant"?: "plain" | "divided" | "outline";
  "items": (UIItem)[];
};

export type UIMap = {
  "type": "map";
  "latitude": number;
  "longitude": number;
  "zoom"?: number;
  "height"?: number;
  "title"?: string | null;
  "caption"?: string | null;
};

export type UIProgress = {
  "type": "progress";
  "label": string;
  "value": number;
  "detail"?: string | null;
};

export type UIProse = {
  "type": "prose";
  "text": string;
};

export type UIQuote = {
  "type": "quote";
  "text": string;
  "attribution"?: string | null;
};

export type UISection = {
  "type": "section";
  "title"?: string | null;
  "description"?: string | null;
  "eyebrow"?: string | null;
  "children": (UIText | UIProse | UIBadge | UILink | UICallout | UILayout | UICard | UISection | UISteps | UIList | UIFacts | UISeparator | UIQuote | UISources | UIProgress | UITable | UIImage | UIFrame | UIMap | UIChart | UIStats | UITimeline)[];
};

export type UISeparator = {
  "type": "separator";
  "label"?: string | null;
};

export type UISource = {
  "label": string;
  "url": string;
  "description"?: string | null;
};

export type UISources = {
  "type": "sources";
  "items": (UISource)[];
};

export type UIStats = {
  "type": "stats";
  "config": StatsBlock;
};

export type UISteps = {
  "type": "steps";
  "items": (string | UIItem)[];
};

export type UITable = {
  "type": "table";
  "columns": (string)[];
  "rows": ((string)[])[];
  "caption"?: string | null;
  "column_widths"?: (number)[] | null;
};

export type UIText = {
  "type": "text" | "heading" | "code" | "mermaid";
  "text": string;
  "variant"?: "body" | "lead" | "muted" | "small";
};

export type UITimeline = {
  "type": "timeline";
  "config": TimelineBlock;
};

export type UIBlock = {
  "title"?: string | null;
  "eyebrow"?: string | null;
  "description"?: string | null;
  "children": (UIText | UIProse | UIBadge | UILink | UICallout | UILayout | UICard | UISection | UISteps | UIList | UIFacts | UISeparator | UIQuote | UISources | UIProgress | UITable | UIImage | UIFrame | UIMap | UIChart | UIStats | UITimeline)[];
};
