"""Keep the browser's message types in sync with the Python validation schema."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from utils.markdown_rich import UIBlock  # noqa: E402

OUTPUT = PROJECT_ROOT / "renderer" / "src" / "message-schema.ts"


def object_type(schema: dict) -> str:
    required = set(schema.get("required", []))
    fields = []
    for name, value in schema.get("properties", {}).items():
        optional = "" if name in required else "?"
        fields.append(f"  {json.dumps(name)}{optional}: {typescript(value)};")
    additional = schema.get("additionalProperties", False)
    if additional:
        fields.append(f"  [key: string]: {typescript(additional) if isinstance(additional, dict) else 'unknown'};")
    return "{\n" + "\n".join(fields) + "\n}"


def typescript(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return " | ".join(dict.fromkeys(typescript(item) for item in schema[union]))
    kind = schema.get("type")
    if kind == "array":
        return f"({typescript(schema['items'])})[]"
    if kind == "object":
        return object_type(schema)
    primitives = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean", "null": "null"}
    if kind in primitives:
        return primitives[kind]
    raise ValueError(f"Unsupported message schema: {schema}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in types differ")
    args = parser.parse_args()
    schema = UIBlock.model_json_schema()
    declarations = [f"export type {name} = {typescript(value)};" for name, value in schema.pop("$defs").items()]
    declarations.append(f"export type UIBlock = {typescript(schema)};")
    content = "// Generated by scripts/generate_renderer_types.py. Do not edit.\n\n" + "\n\n".join(declarations) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("Message types are stale. Run: uv run --locked python scripts/generate_renderer_types.py")
    else:
        OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
